title: Tin tức World Cup 2026 tiếng Việt
description: Cập nhật tự động mỗi giờ từ các nguồn uy tín
baseurl: "" 
url: "https://kaitotakaki.github.io/WC2026"

theme: minima

plugins:
  - jekyll-feed

show_excerpts: true
future: true
